server:
  port: 8080

spring:
  # 【新增】文件上传大小限制
  servlet:
    multipart:
      max-file-size: 6MB      # 单个文件最大 6MB
      max-request-size: 10MB  # 整个请求最大 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/tea_mall?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 1200000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xu.tea.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.xu.tea: debug
tea:
  images:
    path: D:/tea_images/